<a href="https://colab.research.google.com/github/umiSirya/KRA_revenue_optimization/blob/main/KRA_revenue_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importing important libraries
import pandas as pd
import numpy as np

In [5]:
drivers = pd.read_csv('/content/key-revenue-drivers-for-kenya.csv')
taxheads = pd.read_csv('/content/performance-of-key-tax-heads.csv')

# **EDA**

In [6]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revenue Drivers              6 non-null      object
 1   Revenue Collection (Bn Shs)  6 non-null      float64
dtypes: float64(1), object(1)
memory usage: 228.0+ bytes

In [7]:
drivers

                Revenue Drivers  Revenue Collection (Bn Shs)
0                   Tax Amnesty                       43.900
1   Debt collection initiatives                      103.390
2        Betting and Gaming Tax                       24.269
3            Tax Base Expansion                       24.620
4  Dispute resolution framework                       60.469
5      Anti-Corruption Measures                        4.220

In [9]:
taxheads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tax Head               6 non-null      object
 1   Revenue Growth (%)     6 non-null      float64
 2   Tax Revenue (Bn Shs.)  6 non-null      float64
dtypes: float64(2), object(1)
memory usage: 276.0+ bytes

In [10]:
taxheads

            Tax Head  Revenue Growth (%)  Tax Revenue (Bn Shs.)
0  Capital Gains Tax                49.5                  8.381
1  Excise on betting                26.2                 24.269
2    Domestic Excise                 8.1                 73.624
3    Corporation Tax                 4.9                278.156
4       Domestic VAT                15.3                314.157
5               PAYE                 9.7                543.186